# Generated by Django 4.2.1 on 2023-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='rating',
            field=models.FloatField(default=None),
        ),
    ]
