# Generated by Django 4.2.1 on 2023-05-29 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_tasks_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hwk/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
